import Head from 'next/head'
import { Inter } from 'next/font/google'
import Dashboard from '@/components/Dashboard.js/Dashboard'
import Crousal from '@/components/Crousal/Crousal'
import Header from '@/components/Navbar/Header'
import Footer from '@/components/Navbar/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Movie Tickets, Plays, Sports, Events &amp; Cinemas nearby - BookMyShow Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-stone-400'>
       <Header/>
       <Crousal/>
       <Dashboard/>
       <Footer/>
      </main>
    </>
  )
}
